---
- name: Install nginx
  become: true
  ansible.builtin.yum:
    name:
      - nginx

- block:
    - name: Get lighthouse distrib
      ansible.builtin.get_url:
        url: "{{ lighthouse_distrib }}"
        dest: ./lighthouse.zip
    - name: Unpack lighthouse archive
      become: true
      ansible.builtin.unarchive:
        src: ./lighthouse.zip
        dest: /usr/share/nginx
        remote_src: yes
    - name: Nginx configuration
      tags: nginx_config
      become: true
      ansible.builtin.copy:
        dest: /etc/nginx/conf.d/lighthouse.conf
        content: |
          {{ nginx_conf }}
  notify: Start nginx service
